# Generated by Django 3.2.25 on 2024-07-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
