# Generated by Django 3.2.25 on 2024-07-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report',
        ),
    ]
