# Generated by Django 3.2.25 on 2024-07-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_medicine_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='updated_at',
        ),
    ]
