# Generated by Django 3.2.25 on 2024-07-12 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_medicine_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
